version: "3"
services:
  nginx:
    image: nginx:${NGINX_TAG}
    depends_on:
      - php
    ports:
      - ${NGINX_PORT_HOST}:${NGINX_PORT_CONTAINER}
    volumes:
      - ${NGINX_CONF_PATH}:/etc/nginx/conf.d/
      - ${APP_PATH}:/opt/app
    networks:
      - dev-network

  php:
    build: ./php_sources/
    depends_on:
      - mysql
      - redis
      - rabbitmq
    volumes:
      - ${APP_PATH}:/opt/app
    networks:
      - dev-network

  mysql:
    image: mysql:${MYSQL_TAG}
    ports:
      - ${MYSQL_PORT_HOST}:3306
    volumes:
      - ${MYSQL_VOLUME_PATH}:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    networks:
      - dev-network

  redis:
    image: redis:${REDIS_TAG}
    ports:
      - ${REDIS_PORT_HOST}:6379
    volumes:
      - ${REDIS_VOLUME_PATH}:/data
    networks:
      - dev-network

  rabbitmq:
    image: rabbitmq:${RABBITMQ_TAG}
    ports:
      - ${RABBITMQ_PORT_HOST}:5672 
      - ${RABBITMQ_MANAGEMENT_PORT_HOST}:15672
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    networks:
      - dev-network


networks:
  dev-network:

